linebot:
  token: "Line_Bot_Token"
  secret: "Line_Bot_Secret"
  userId: "Your_Line_UserId"
port: "8080"

mongo:
  URI: "mongodb://localhost:27017"
  DataBase: "LineBot"
  MessageCollection: "MessageLog"
  Credential:
    AuthMechanism: "SCRAM-SHA-256"
    AuthSource: "LineBot"
    Username: "sa"
    Password: "pass.123"